name: HoneyBadger
version: "#e2faeb5"
info: An analysis tool to detect honeypots in Ethereum smart contracts
origin: https://github.com/smartbugs/HoneyBadger
image: smartbugs/honeybadger:e2faeb5
bin: scripts
solidity:
    entrypoint: "'$BIN/do_solidity' '$FILENAME' '$TIMEOUT' '$BIN' '$MAIN'"
    solc: yes
runtime:
    entrypoint: "'$BIN/do_runtime' '$FILENAME' '$TIMEOUT'"
